frontend/__init__.py
# from flask import Flask
# #from flask_login import LoginManager
# #from flask_sqlalchemy import SQLAlchemy

# #login_manager = LoginManager()
# #db = SQLAlchemy()


# def create_app():
#     app = Flask(__name__)

#     app.config['SECRET_KEY'] = '7110c8ae51a4b5af97be6534caef90e4bb9bdcb3380af008f90b23a5d1616bf319bc298105da20fe'
#     app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test.db'
#     #app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

#     # login_manager.init_app(app)
#     # login_manager.login_view = "auth.login"

#     #db.init_app(app)
    
#     from .routes import front
#     from .app.routes import supervoices
#     # from apps.user.routes import user
    
#     app.register_blueprint(front,url_prefix='')
#     app.register_blueprint(front,url_prefix='/login')
#     app.register_blueprint(supervoices,url_prefix='/supervoice')
#     # app.register_blueprint(user,url_prefix='/user')

#     return app

frontend/app/routes.py
from flask import Blueprint, render_template

supervoices = Blueprint("supervoices",__name__,template_folder="templates/app",static_folder="static/app",static_url_path="static/app")


@supervoices.route("/")
def supervoice():
    return render_template("app/baseapp.html")

frontend/routes.py
from flask import Blueprint, redirect, render_template, request, url_for

front = Blueprint("front",__name__,template_folder="templates/front",static_folder='static/front',static_url_path="static/front")

@front.route("/")
def home():
    return render_template("home.html")



@front.route("/login",methods=['GET','POST'])
def login():

    if request.method=="GET":    
        return render_template("login.html")
    print("hola mundo")
    return redirect(url_for("supervoices.supervoice"))
    

frontend/templates/app/baseapp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'app/css/style.css') }}">
    <!-- <link rel="stylesheet" href="/static/app/css/style.css"> -->
    <title>Document</title>
</head>
<body>
    <h1><p>supervoices</p></h1>
</body>
<script src="{{ url_for('static', filename= 'app/js/holamundo.js') }}"></script>
</html>

frontend/templates/front/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Supervoices G12</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ url_for('front.static', filename= 'img/favicon.png') }}" rel="icon">
  <link href="{{ url_for('front.static', filename= 'img/apple-touch-icon.png') }}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('front.static', filename= 'vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('front.static', filename= 'vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ url_for('front.static', filename= 'vendor/aos/aos.css') }}" rel="stylesheet">
  <link href="{{ url_for('front.static', filename= 'vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('front.static', filename= 'css/variables.css') }}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{ url_for('front.static', filename= 'css/main.css') }}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top" data-scrollto-offset="0">
    <div class="container-fluid d-flex align-items-center justify-content-between">

      <a href="/" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
        <h1>Super<span>Voices.</span></h1>
      </a>

      <nav id="navbar" class="navbar">
        {% block navegacion %} {% endblock %}
        <i class="bi bi-list mobile-nav-toggle d-none"></i>
      </nav>

      <a class="btn-getstarted scrollto" href="/login">login</a>

    </div>
  </header>

  {% block body %} {% endblock %}

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-content">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <h3>HeroBiz</h3>
              <p>
                A108 Adam Street <br>
                NY 535022, USA<br><br>
                <strong>Phone:</strong> +1 5589 55488 55<br>
                <strong>Email:</strong> info@example.com<br>
              </p>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>

          </div>

        </div>
      </div>
    </div>

    <div class="footer-legal text-center">
      <div class="container d-flex flex-column flex-lg-row justify-content-center justify-content-lg-between align-items-center">

        <div class="d-flex flex-column align-items-center align-items-lg-start">
          <div class="copyright">
            &copy; Copyright <strong><span>HeroBiz</span></strong>. All Rights Reserved
          </div>
          <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/herobiz-bootstrap-business-template/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
          </div>
        </div>

        <div class="social-links order-first order-lg-last mb-3 mb-lg-0">
          <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
          <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
          <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
          <a href="#" class="google-plus"><i class="bi bi-skype"></i></a>
          <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
        </div>

      </div>
    </div>

  </footer><!-- End Footer -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{{ url_for('front.static', filename= 'vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('front.static', filename= 'vendor/aos/aos.js') }}"></script>
  <script src="{{ url_for('front.static', filename= 'vendor/glightbox/js/glightbox.min.js') }}"></script>
  <script src="{{ url_for('front.static', filename= 'vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
  <script src="{{ url_for('front.static', filename= 'vendor/swiper/swiper-bundle.min.js') }}"></script>
  <script src="{{ url_for('front.static', filename= 'vendor/php-email-form/validate.js') }}"></script>

  <!-- Template Main JS File -->
  <script src="{{ url_for('front.static', filename= 'js/main.js') }}"></script>

</body>

</html>

frontend/templates/front/home.html
{% extends 'front/base.html' %}

{% block navegacion %}
    <ul>
        <li class="dropdown"><a href="#"><span>Home</span> </i></a>
        <!-- <li><a class="nav-link scrollto" href="index.html#contact">Crear cuenta</a></li> -->
    </ul>
{% endblock %}

{% block body %} 
<section id="hero-static" class="hero-static d-flex align-items-center">
    <div class="container d-flex flex-column justify-content-center align-items-center text-center position-relative" data-aos="zoom-out">
      <h2>Bienvenidos a <span>SUPERVOICES</span></h2>
      <p>El super concurso de voces</p>
      <div class="d-flex">
        <a href="#contact" class="btn-get-started scrollto">CREAR CUENTA</a>
        <!-- <a href="https://www.youtube.com/watch?v=LXb3EKWsInQ" class="glightbox btn-watch-video d-flex align-items-center"><i class="bi bi-play-circle"></i><span>Watch Video</span></a> -->
      </div>
    </div>
  </section>

  <main id="main">


    <section id="featured-services" class="featured-services">
      <div class="container">

        <div class="row gy-4">

          <div class="col-xl-3 col-md-6 d-flex" data-aos="zoom-out">
            <div class="service-item position-relative">
              <div class="icon"><i class="bi bi-activity icon"></i></div>
              <h4><a href="" class="stretched-link">Lorem Ipsum</a></h4>
              <p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi</p>
            </div>
          </div><!-- End Service Item -->

          <div class="col-xl-3 col-md-6 d-flex" data-aos="zoom-out" data-aos-delay="200">
            <div class="service-item position-relative">
              <div class="icon"><i class="bi bi-bounding-box-circles icon"></i></div>
              <h4><a href="" class="stretched-link">Sed ut perspici</a></h4>
              <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>
            </div>
          </div><!-- End Service Item -->

          <div class="col-xl-3 col-md-6 d-flex" data-aos="zoom-out" data-aos-delay="400">
            <div class="service-item position-relative">
              <div class="icon"><i class="bi bi-calendar4-week icon"></i></div>
              <h4><a href="" class="stretched-link">Magni Dolores</a></h4>
              <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia</p>
            </div>
          </div><!-- End Service Item -->

          <div class="col-xl-3 col-md-6 d-flex" data-aos="zoom-out" data-aos-delay="600">
            <div class="service-item position-relative">
              <div class="icon"><i class="bi bi-broadcast icon"></i></div>
              <h4><a href="" class="stretched-link">Nemo Enim</a></h4>
              <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis</p>
            </div>
          </div><!-- End Service Item -->

        </div>

      </div>
    </section><!-- End Featured Services Section -->


        <!-- ======= Contact Section ======= -->
        <section id="contact" class="contact">
            <div class="container">
      
              <div class="section-header">
                <h2>Formulario crear cuenta</h2>
                <p>Diligencie este formulario para crear una cuenta con nosotros</p>
              </div>
      
            </div>

            <div class="container">
                <div class="col-lg-12">
                  <form action="forms/contact.php" method="post" role="form" class="php-email-form">
                    <div class="row">
                      <div class="col-md-6 form-group">
                        <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                      </div>
                      <div class="col-md-6 form-group mt-3 mt-md-0">
                        <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
                      </div>
                    </div>
                    <!-- <div class="form-group mt-3">
                      <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
                    </div> -->
                    <!-- <div class="form-group mt-3">
                      <textarea class="form-control" name="message" placeholder="Message" required></textarea>
                    </div> -->
                    <!-- <div class="my-3">
                      <div class="loading">Loading</div>
                      <div class="error-message"></div>
                      <div class="sent-message">Your message has been sent. Thank you!</div>
                    </div> -->
                    <div class="text-center"><button type="submit">INSCRIBIRSE</button></div>
                  </form>
                </div><!-- End Contact Form -->
      
              </div>
      
            </div>
          </section><!-- End Contact Section -->


  </main><!-- End #main -->


{% endblock %}

frontend/templates/front/login.html
{% extends 'front/base.html' %}



{% block body %} 
        
        
<section id="contact" class="contact">
    <div class="container">
      <div class="section-header">
        <h2>INGRESAR A SUPERVOICES</h2>
        <p></p>
      </div>
    </div>

    <div class="text-center container">

        <div class="container">
            <div class="col-lg-12">
              <form  method="POST" action="{{url_for('front.login')}}" >
                <div class="row">
                  <label  class="col-md-2 col-form-label">Email</label>
                  <div class="col-md-6 form-group">
                    <input type="text" name="usuario" class="form-control" id="name" placeholder="usuario" required>
                  </div>
                </div>
                <div class="row">
                    <label  class="col-md-2 col-form-label">Password</label>
                    <div class="col-md-6 form-group">
                        <input type="password" name="password" class="form-control" id="name" placeholder="password" required>
                    </div>
                </div>
                <br>
                <div class="text-center"><button type="submit" href="{{url_for('front.login')}}">INGRESAR</button></div>
              </form>
            </div>
    
        </div>

    </div>
  </section>
 
  <br><br><br><br>

{% endblock %}